# Generated by Django 5.1.5 on 2025-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ManyToManyField(related_name='project', to='main.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('po', 'Po'), ('developer', 'Developer'), ('tester', 'Tester')], default='developer', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='TeamProject',
        ),
    ]
