# Generated by Django 5.1.5 on 2025-03-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_team_user_team_id_team_project_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
    ]
